version: '{build}'
skip_tags: true
image: Visual Studio 2022
install:
  - ps: mkdir -Force ".\build\" | Out-Null
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
only_commits:
  files:
    - serilog-sinks-compact-reader.sln
    - src/Serilog.Sinks.Compact.Reader/
    - Build.ps1
    - assets/
    - test/Serilog.Formatting.Compact.Reader.Tests/
deploy:
- provider: NuGet
  api_key:
    secure: pXU3a6E4Uw0FJdGVwt+GP5XCjYU5KDUe6XWE77fWk6K0ujid44X9EbIYxhrhChbu
  skip_symbols: true
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
    
